//auditEnum.js

const AUDIT_MODULES = {
  USER: "USER",
  DEALER: "DEALER",
  INDUSTRY: "INDUSTRY",
  ORDER: "ORDER",
  ORDER_ITEM: "ORDER_ITEM",
  CATEGORY: "CATEGORY",
  PRODUCT: "PRODUCT",
  QUOTATION: "QUOTATION",
  QUOTATION_ITEM: "QUOTATION_ITEM",
  AUTH: "AUTH",
};

const AUDIT_ACTIONS = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  SOFT_DELETE: "SOFT_DELETE",

  STATUS_CHANGE: "STATUS_CHANGE",
  ASSIGNMENT_CHANGE: "ASSIGNMENT_CHANGE",

  APPROVE: "APPROVE",
  REJECT: "REJECT",

  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  PASSWORD_RESET: "PASSWORD_RESET",
  EMAIL_VERIFY: "EMAIL_VERIFY",

  EXPORT: "EXPORT",
  IMPORT: "IMPORT",
};

module.exports = {
  AUDIT_MODULES,
  AUDIT_ACTIONS,
};