const productCategory=require("./ProductCategory");
const userModel=require("./UserModel");
const subCategory=require("./SubCategory");
const quotationModel=require("./QuotationModel");
const quotationItem=require("./QuotationItem")
const dealerModel=require("./DealerModel");
const productModel=require("./ProductModel");
const industryModel=require("./IndustryModel");
const orderItemModel=require("./OrderItem")
const orderModel=require("./Order")
module.exports={productCategory,userModel,subCategory,quotationModel,quotationItem,orderItemModel,dealerModel,productModel,industryModel,orderModel};
