const productCategory=require("./ProductCategory");
const userModel=require("./UserModel");
const subCategory=require("./SubCategory");
const quotationModel=require("./QuotationModel");
const quotationItem=require("./QuotationItem")
const dealerModel=require("./DealerModel");
const productModel=require("./ProductModel");
const industryModel=require("./IndustryModel")
module.exports={productCategory,userModel,subCategory,quotationModel,quotationItem,dealerModel,productModel,industryModel};
